# Generated by Django 3.1.7 on 2021-02-28 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
