# Generated by Django 3.1.7 on 2021-03-08 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('text', models.TextField(blank=True, max_length=256)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
