# Generated by Django 3.1.7 on 2021-03-08 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='text',
            field=models.TextField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.projects')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
