# Generated by Django 3.1.7 on 2021-04-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210401_1400'),
        ('todo_app', '0002_auto_20210308_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
